from fastapi import APIRouter, Depends, HTTPException, status, Request
from sqlmodel import Session, select, create_engine
import asyncio, httpx

from app.models.product import Product, ProductCreate
from app.core.database import get_session, engine
from app.routers.auth import get_current_user, RoleChecker
from app.models.user import User


router = APIRouter()

@router.get('/products')
def read_products():
    with Session(engine) as session:
        query = select(Product)
        result = session.exec(query)
        all_products = result.all()
        return all_products


@router.get('/products/{product_id}')
def read_product_by_id(product_id: int):
    with Session(engine) as session:
        query = select(Product).where(Product.id == product_id)
        result = session.exec(query)
        product_by_id = result.first()
        if product_by_id:
            return product_by_id
        raise HTTPException(status.HTTP_404_NOT_FOUND, detail='Product not found')


@router.delete('/products/{product_id}')
def delete_product_by_id(
    product_id: int,
    session: Session = Depends(get_session),
    role_checker = Depends(RoleChecker(allowed_roles=['admin']))
):
    query = select(Product).where(Product.id == product_id)
    result = session.exec(query)
    target_product = result.first()
    if not target_product:
        raise HTTPException(status.HTTP_404_NOT_FOUND, detail='Product not found')
    session.delete(target_product)
    session.commit()
    return {'status': 'success', 'message': 'Product deleted'}


@router.put('/products/{product_id}')
def update_product(product_id: int, product_data: ProductCreate, session: Session = Depends(get_session), current_user: User = Depends(get_current_user)):
    query = select(Product).where(Product.id == product_id)
    result = session.exec(query)
    target_product = result.first()
    if not target_product:
        raise HTTPException(status.HTTP_404_NOT_FOUND, detail='Product not found')
    target_product.title = product_data.title
    target_product.price = product_data.price
    session.commit()
    session.refresh(target_product)
    return target_product


@router.post('/product')
def create_product(product: ProductCreate, current_user: User = Depends(get_current_user), session: Session = Depends(get_session)):
    query = select(Product).where(Product.title == product.title)
    target_product = session.exec(query).first()
    if target_product:
        raise HTTPException(status.HTTP_400_BAD_REQUEST, detail='This product name already exists')
    new_product = Product(title=product.title, price=product.price)
    session.add(new_product)
    session.commit()
    session.refresh(new_product)
    return new_product


@router.post('/products/{product_id}/generate-ai-description')
async def get_ai_description(product_id: int, request: Request, session: Session = Depends(get_session), role_checker = Depends(RoleChecker(allowed_roles=['admin', 'manager']))):
    client: httpx.AsyncClient = request.app.state.http_client
    response = await client.get('https://httpbin.org/delay/2')
    if response.status_code != 200:
        raise HTTPException(status.HTTP_503_SERVICE_UNAVAILABLE, detail='AI service is temporarily unavailable')
    data = response.json()

    query = select(Product).where(product_id == Product.id)
    target_product = session.exec(query).first()
    if not target_product:
        raise HTTPException(status.HTTP_404_NOT_FOUND, detail='Product not found')
    model_name = request.app.state.ai_model_name
    ai_text = f'This is a stunning marketing description for {target_product.title}, automatically generated by {model_name}. Fetched from {data['url']}.'
    return {'product_id': product_id, 'ai_description': ai_text}